services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - jcg_data:/data
    restart: unless-stopped
    environment:
      - JCG_SEED_PLAYERS=Michael,Dan,James,Mark
      - JCG_SEED_USERS=admin:test

volumes:
  jcg_data:
